version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://timur:123@db:5432/tasks_db
      - REDIS_URL=redis://redis:6379/0  # Добавляем переменную для Redis
      - DEBUG=1
      - SECRET_KEY='timur:123'
    depends_on:
      - db
      - redis
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge